-- Global shared instruction exclusions used only for UI filtering

create table if not exists public.instruction_exclusions_v2 (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  created_by uuid not null references public.users(id) on delete cascade,
  raw_text text not null,
  normalized_text text not null,
  is_active boolean not null default true
);

create unique index if not exists instruction_exclusions_v2_normalized_text_uq
  on public.instruction_exclusions_v2 (normalized_text)
  where is_active = true;

alter table public.instruction_exclusions_v2 enable row level security;

drop policy if exists "read exclusions" on public.instruction_exclusions_v2;
create policy "read exclusions"
on public.instruction_exclusions_v2
for select
to authenticated
using (true);

drop policy if exists "pm_admin insert exclusions" on public.instruction_exclusions_v2;
create policy "pm_admin insert exclusions"
on public.instruction_exclusions_v2
for insert
to authenticated
with check (
  exists (
    select 1 from public.users u
    where u.id = auth.uid()
      and u.role in ('pm','admin')
  )
);

drop policy if exists "pm_admin update exclusions" on public.instruction_exclusions_v2;
create policy "pm_admin update exclusions"
on public.instruction_exclusions_v2
for update
to authenticated
using (
  exists (
    select 1 from public.users u
    where u.id = auth.uid()
      and u.role in ('pm','admin')
  )
)
with check (
  exists (
    select 1 from public.users u
    where u.id = auth.uid()
      and u.role in ('pm','admin')
  )
);

drop policy if exists "pm_admin delete exclusions" on public.instruction_exclusions_v2;
create policy "pm_admin delete exclusions"
on public.instruction_exclusions_v2
for delete
to authenticated
using (
  exists (
    select 1 from public.users u
    where u.id = auth.uid()
      and u.role in ('pm','admin')
  )
);

-- Optional best-effort backfill from legacy table
insert into public.instruction_exclusions_v2 (created_by, raw_text, normalized_text)
select user_id, instruction_text, lower(trim(instruction_text))
from public.instruction_exclusions
on conflict do nothing;